### ISSUE TITLE
Probably remove the unneeded random draw in APICaffe::ThreadFillerBase

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#37]
Wouldn't consider it super urgent, though.

**Comment by twongjirad** [comment]
Or entry in process_entry( entry) should mean tree index. There is probably a reason why the different indexing is needed, though, that I fail to see.

**Comment by drinkingkazu** [comment]
I actually remembered why this feature exists: it is because "RandomAccess" configuration parameter is shared among ThreadDatumFiller and underlying IOManager (actually ProcessDriver, which owns IOManager). I'll change it such that ThreadDatumFiller creates its own IO configuration deterministically and never use RandomAccess (ThreadDatumFiller will decide randomness). This way index ThreadDatumFiller thinks = actual index in TTree.

**Comment by drinkingkazu** [comment]
Addressed: https://github.com/LArbys/LArCV/commit/29ea5ed78475c6656c9f68410962cb10d1ecb6aa

Closing this issue.
