### ISSUE TITLE
minor: app objects rebuild when typing make, even if nothing changes

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#69]
I typed make. everything built and was fine.

I type make again, and the following rebuilds:
- Filters
- PMTWeightImageBuilder
- HiResDivider
- Merger

Minor issue as everything still works. Just uses up more time than is necessary?

**Comment by drinkingkazu** [comment]
Is this possibly on an old larcv installation? There was this issue in an older version of larcv, and this can be fixed by doing this:

`cd $LARCV_BASEDIR`
`rm core/*/*.depend`
`rm app/*/*.depend`
`make -j`

But for a new installation I do not expect this to happen.
Here, by "old vs. new", I meant before vs. after apicaffe_cleanup branch merge into develop.
Would you give a shot?

**Comment by twongjirad** [comment]
turns out that I did have .depend files in the apps that were rebuilding. Once removed, this issue no longer remains. Thanks!
