### ISSUE TITLE
investigate process: PMTWeight doing its job?

### ISSUE THREAD

**Issue by drinkingkazu** [LArbys/LArCV#9]
Need to check if PMTWeight is applied correctly...

**Comment by twongjirad** [comment]
Turns out, no. But I've fixed it!  See: c65c33167ce36283d9c221e412ecdcbd432fcac3

Demonstration of the fixed behavior:

TPC image:

![pmtweighting_ex_tpc_yview_newscale](https://cloud.githubusercontent.com/assets/7130028/16993366/a824144e-4e68-11e6-9e9c-5a24e77008d7.png)

PMT Weighted:

![pmtweighting_ex_pmtweighted_yview_newscale](https://cloud.githubusercontent.com/assets/7130028/16993352/972d1b2c-4e68-11e6-8586-ec20232416e5.png)

Much better than before, which was just wrong.

One potential issue to keep in mind though. The weights oscillate pretty rapidly, just due to the use of 1/d for the weight. This is the weight mask used for the above PMT-weighted image:

![pmtweighting_pmtmask_pmtweighted_yview_newscale](https://cloud.githubusercontent.com/assets/7130028/16993402/e235dafa-4e68-11e6-9be5-ca186989da81.png)
